petstagram/petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts.views import SignupUser, \
    PetstagramLoginView, PetstagramLogoutView, \
    ProfileEditView, ProfileDetailsView , ProfileDeleteView

urlpatterns = (
    path("signup/", SignupUser.as_view(), name="signup_user"),
    path("signin/", PetstagramLoginView.as_view(), name="signin_user"),
    path("signout/", PetstagramLogoutView.as_view(), name="signout_user"),
    path("profile/<int:pk>/", include([
        path("", ProfileDetailsView.as_view(), name="details_profile"),
        path("edit/", ProfileEditView.as_view(), name="edit_profile"),
        path("delete/", ProfileDeleteView.as_view(), name="delete_profile"),

    ])),
)

petstagram/petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("petstagram.common.urls")),
    path('accounts/', include("petstagram.accounts.urls")),
    path('pets/', include("petstagram.pets.urls")),
    path('photos/', include("petstagram.photos.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/petstagram/accounts/models.py
from django.contrib.auth import models as auth_models
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from petstagram.accounts.managers import PetstagramUserManager


class PetstagramUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    email = models.EmailField(
        _("email address"),
        unique=True,
        error_messages={
            "unique": _("A user with that email already exists.")
        }
    )

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = PetstagramUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(
        PetstagramUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    profile_picture = models.URLField(blank=True, null=True)

    def get_profile_name(self):
        if self.get_full_name() != "None None":
            return self.get_full_name()
        return "Anonymous User"

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

petstagram/petstagram/pets/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify

UserModel = get_user_model()


class Pet(models.Model):
    MAX_NAME_LENGTH = 30

    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
    )

    pet_photo = models.URLField()

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    slug = models.SlugField(
        unique=True,
        null=False,
        blank=True,
        editable=False
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.id}")

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

petstagram/petstagram/photos/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, BaseValidator
from django.db import models

from petstagram.pets.models import Pet

SIZE_5_MB = 5 * 1024 * 1024

UserModel = get_user_model()


class ImageSizeValidator(BaseValidator):

    def __init__(self, limit_value):
        super().__init__(limit_value,
                         f"The maximum file size that can be uploaded is {limit_value / 1024 / 1024:.0f} MB.")

    def compare(self, file_size, max_size):
        return file_size > max_size

    def clean(self, x):
        return x.size


def validate_file_size_less_than_5_mb(value):
    if value.size > SIZE_5_MB:
        raise ValidationError("The maximum file size that can be uploaded is 5 MB.")


class PetPhoto(models.Model):
    MAX_DESCRIPTION_LENGTH = 300
    MAX_LOCATION_LENGTH = 300
    MIN_DESCRIPTION_LENGTH = 10

    photo = models.ImageField(
        upload_to="pet_photos/",
        validators=[
            # validate_file_size_less_than_5_mb,
            ImageSizeValidator(SIZE_5_MB)
        ],
    )  # pip install Pillow

    description = models.TextField(
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=[MinLengthValidator(MIN_DESCRIPTION_LENGTH), ],
        null=True,
        blank=True
    )

    location = models.CharField(max_length=MAX_LOCATION_LENGTH)

    pets = models.ManyToManyField(Pet)

    created_at = models.DateTimeField(auto_now_add=True)

    modified_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

petstagram/petstagram/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import forms as auth_forms

from petstagram.accounts.models import Profile

UserModel = get_user_model()


class CreateUserForm(auth_forms.BaseUserCreationForm):
    # if not created custom filter to add placeholder to form fields
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields["email"].widget.attrs['placeholder'] = 'Email'
    #     self.fields["password1"].widget.attrs['placeholder'] = 'Password'
    #     self.fields["password2"].widget.attrs['placeholder'] = 'Repeat Password'

    class Meta:
        model = UserModel
        fields = ['email', 'password1', 'password2']


class PetstagramUserChangeForm(auth_forms.UserChangeForm):
    class Meta(auth_forms.UserChangeForm.Meta):
        model = UserModel
        fields = '__all__'


class PetstagramUserLoginForm(auth_forms.AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={"autofocus": True}))


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'date_of_birth', 'profile_picture']
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'date_of_birth': 'Date of Birth (YYYY-MM-DD)',
            'profile_picture': 'Profile Picture',
        }

petstagram/petstagram/accounts/views.py
from django.contrib.auth import mixins as auth_mixins
from django.contrib.auth import get_user_model, login
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from petstagram.accounts.forms import CreateUserForm, PetstagramUserLoginForm, ProfileEditForm
from petstagram.accounts.models import Profile

UserModel = get_user_model()


class SignupUser(views.CreateView):
    model = UserModel
    form_class = CreateUserForm
    template_name = "accounts/signup_user.html"
    success_url = reverse_lazy("index")


class PetstagramLoginView(auth_views.LoginView):
    form_class = PetstagramUserLoginForm
    template_name = "accounts/signin_user.html"
    redirect_authenticated_user = True


class PetstagramLogoutView(auth_views.LogoutView):
    pass


class ProfileEditView(auth_mixins.LoginRequiredMixin, views.UpdateView):
    model = UserModel
    form_class = ProfileEditForm
    template_name = "accounts/edit_profile.html"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_success_url(self):
        return reverse_lazy("details_profile", kwargs={"pk": self.object.pk})


class ProfileDetailsView(auth_mixins.LoginRequiredMixin, views.DetailView):
    model = Profile
    template_name = "accounts/details_profile.html"

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_likes"] = sum([photo.photolike_set.count() for photo in self.object.user.petphoto_set.all()])
        return context


class ProfileDeleteView(auth_mixins.LoginRequiredMixin, views.DeleteView):
    model = UserModel
    template_name = "accounts/delete_profile.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return self.request.user

petstagram/templates/accounts/delete_profile.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
    <main>

        <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <form method="post">
                    <button>Yes</button>
                    {% csrf_token %}
                </form>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="{% static '/images/are_you_sure_cat.gif' %}" alt="are you sure cat git">
        </div>
        <!-- End Delete Profile Section -->

    </main>
{% endblock %}

petstagram/templates/accounts/details_profile.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}

    <main>
        <!-- Start Profile Details Section -->
        <div class="profile">
            <!-- Start Profile Personal Data Section -->
            <div class="profile-data">
                <div class="profile_img">
                    {% if object.profile_picture %}
                        <div class="image">
                            <!-- User Profile Image -->
                            <img src="{{ object.profile_picture }}" alt="img8">
                        </div>
                    {% else %}
                        <div class="image">
                            <!-- Default User Profile Image -->
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    {% endif %}
                </div>
                <div class="personal">
                    <div class="edit">
                        <!-- User Username -->
                        <p>{{ object.first_name }} {{ object.last_name }}</p>

                        <!-- IF the viewer is the owner of the profile -->

                        {% if request.user == object.user %}

                            <!-- Link to Edit Profile Page -->
                            <a href="{% url 'edit_profile' pk=request.user.pk %}">
                                <img
                                        class="edit-img"
                                        src="{% static '/images/edit-pen-icon-6.jpg' %}"
                                        alt="edit button"
                                />
                            </a>

                            <!-- Link to Delete Profile Page -->
                            <a href="{% url 'delete_profile' pk=request.user.pk%}">
                                <img
                                        class="bin-img"
                                        src="{% static '/images/icon-remove-22.jpg' %}"
                                        alt="bin button"
                                />
                            </a>
                            <!-- End IF the viewer is the owner of the profile -->
                        {% endif %}
                    </div>
                    <div class="data">
                        <!-- Total Number of Photos by the User -->
                        <span>{{ object.user.petphoto_set.count }} </span>
                        <p>photos</p>

                        <!-- Total Number of Pets owned by the User -->
                        <span>{{ object.user.pet_set.count }}</span>
                        <p>pets</p>

                        <!-- Total Number of Likes for the User -->
                        <span>{{ total_likes }}</span>
                        <p>likes</p>
                    </div>
                    <!-- User First and Last Name IF Added -->
                    <h3 class="names">{{ object.first_name }} {{ object.last_name }}</h3>

                    <!-- User Email Address -->
                    <p class="email">{{ object.user.email }}</p>

                </div>
            </div>
            <!-- End Profile Personal Data Section -->

            <!-- Start Pets Data Section -->

            <div class="pets">
                <div class="statuses">
                    <!-- Start Pets Details Page -->
                    {% for pet in object.user.pet_set.all %}
                        <!-- Link Pet Details Page -->
                        <a href="{% url 'details pet' username=pet.user.profile.get_profile_name slug=pet.slug %}">
                            <div class="head-pet">
                                <div class="status">
                                    <div class="image">
                                        <!-- Pet Image -->
                                        <img
                                                src="{{ pet.pet_photo }}"
                                                alt="pet img"
                                        />
                                    </div>
                                </div>
                                <!-- Pet Name -->
                                <p>{{ pet.name }}</p>
                            </div>
                        </a>
                        <!-- End 1st Pet Details Page -->
                    {% endfor %}
                </div>
            </div>
            <!-- End Pets Data Section -->


            <!-- Start Last Uploaded Photos Section -->
            <div class="pet-photos">

                {% for pet_photo in object.user.petphoto_set.all|dictsortreversed:"created_at" %}

                    <!-- Link to Last Uploaded Pet Photo -->
                    <a href="{% url 'details photo' pet_photo.pk %}">
                        <!-- Pet Photo -->
                        <img
                                src="{{ pet_photo.photo.url }}"
                                alt="pet img"
                        />
                    </a>

                {% empty %}
                                <!-- IF NO Posts Show No Post Image -->
                    <img
                            class="no-posts"
                            src="{% static '/images/no_posts.png' %}"
                            alt="no posts"
                    />
                {% endfor %}
            </div>
        </div>
        <!-- End Profile Details Section -->
    </main>

{% endblock %}

petstagram/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load custom_filter %}
{% load static %}
{% block main_content %}
    <main>
        <!-- Start Edit Profile Section -->
        <div class="edit-delete">
            <h2>Edit Profile</h2>
            <!-- Start Edit Profile From -->
            <form action="{% url 'edit_profile' pk=request.user.pk %}" method="post">
                <div class="label-input">
                    <p class="error">{{ form.first_name.errors }}</p>
                    <label for="first name">First name: </label>
                    {{ form.first_name }}
                </div>
                <br>
                <div class="label-input">
                    <label for="last name">Last name: </label>
                    {{ form.last_name }}
                </div>
                <br>
                <div class="label-input">
                    <p class="error">{{ form.date_of_birth.errors }}</p>
                    <label for="date of birth">Date of Birth: </label>
                    {{ form.date_of_birth|placeholder:"YYYY-MM-DD" }}
                </div>
                <br>
                <div class="label-input">
                    <label for="profile picture">Profile Picture: </label>
                    {{ form.profile_picture|placeholder:"Picture URL" }}
                </div>


                <!-- Edit Profile Button -->
                <button class="edit-btn" type="submit">Edit</button>
                {% csrf_token %}
            </form>
            <!-- End Edit Profile Form -->

        </div>
        <!-- End Edit Profile Section -->

    </main>
{% endblock %}

petstagram/templates/accounts/signin_user.html
{% extends "base.html" %}
{% load custom_filter %}
{% load static %}
{% block main_content %}
    <!-- Starts Main Section -->
    <main>

        <!-- Start Login Section-->
        <div class="login-register-div">
            <div class="login-register-box">
                <h1>Petstagram</h1>

                <!-- Start Login Form-->
                <form method="post">
                    <div class="alert alert-danger" role="alert">
                        <ul style="list-style: none">
                            {% for field, error in form.errors.items %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {{ form.username|placeholder:"Email" }}
                    {{ form.username.errors }}
                    {{ form.password|placeholder:"Password" }}
                    {{ form.password.errors }}

                    {% csrf_token %}

                    <!-- Login Button-->
                    <button type="submit">Log in</button>
                </form>
                <!-- End Login Form -->

            </div>
            <div class="second-option">

                <!-- Link to Register Page-->
                <p>Don't have an account? <a href="{% url "signup_user" %}">Register</a></p>
            </div>
        </div>
        <!-- End Login Section-->

    </main>
    <!-- End Main Section -->
{% endblock %}

petstagram/templates/accounts/signup_user.html
{% extends "base.html" %}
{% load custom_filter %}
{% load static %}
{% block main_content %}
    <!-- Starts Main Section -->
    <main>

        <!-- Start Register Section -->
        <div class="login-register-div">
            <div class="login-register-box">
                <h1>Petstagram</h1>

                <!-- Start Register Form -->
                <form method="post">
                    {{ form.email|placeholder:"Email" }}    <!-- Email Field -->
                    {{ form.email.errors }} <!-- Email Error -->
                    
                    {{ form.password1|placeholder:"Password" }} <!-- Password Field -->
                    {{ form.password1.errors }} <!-- Password Error -->
                    {{ form.password2|placeholder:"Repeat Password" }} <!-- Confirm Password Field -->
                    {{ form.password2.errors }} <!-- Confirm Password Error -->

                    <!-- Register Button -->
                    <button type="submit">Register</button>
                    {% csrf_token %}
                </form>
                <!-- End Register Form -->

            </div>
            <div class="second-option">

                <!-- Link to Login Page -->
                <p>Have an account? <a href="{% url "signin_user" %}">Log in</a></p>
            </div>
        </div>
        <!-- End Register Section -->

    </main>
    <!-- End Main Section -->
{% endblock %}