petstagram/petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("petstagram.common.urls")),
    path('accounts/', include("petstagram.accounts.urls")),
    path('pets/', include("petstagram.pets.urls")),
    path('photos/', include("petstagram.photos.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from petstagram.photos.models import PetPhoto

UserModel = get_user_model()


class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.TextField(
        max_length=MAX_TEXT_LENGTH,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
    )

    pet_photo = models.ForeignKey(
        PetPhoto,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )


class PhotoLike(models.Model):
    pet_photo = models.ForeignKey(
        PetPhoto,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )



# photo_like = PhotoLike.objects.filter(pet_photo_id=pet_photo.pk, user=request.user)

petstagram/templates/partials/pet_photo_list_items.html
{% load photo_likes %}
{% load static %}
{% load static %}

<div class="card">
    <div class="top">
        <!-- User Details and image location -->
        <div class="userDetails">
            <a href="{% url 'details_profile' pk=photo.user_id %}">
                <div class="profilepic">
                    <div class="profile_img">
                        {% if photo.user.profile.profile_picture %}
                            <div class="image">
                                <!-- User Profile Image -->
                                <img src="{{ photo.user.profile.profile_picture }}" alt="img8">
                                
                            </div>
                        {% else %}
                            <div class="image">
                                <!-- Default User Profile Image -->
                                <img src="{% static 'images/person.png' %}" alt="img8">
                            </div>
                        {% endif %}
                    </div>
                </div>
            </a>
            <h3>
                <a href="{% url 'details_profile' pk=photo.user.pk %}">
                    <!-- if user has first name and last name -->
                    {{ photo.user.profile.get_profile_name }}
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}

                <!-- IF the viewer is the creator of the photo -->
                {% if request.user == photo.user %}
                    <div class="edit-delete-btns">

                        <!-- Link to Edit Pet Photo Page -->
                        <a href="{% url 'edit photo' pk=photo.pk %}">
                            <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                 alt="edit button">
                        </a>

                        <!-- Link to Delete Pet Photo Page -->
                        <a href="{% url 'delete photo' pk=photo.pk %}">
                            <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                        </a>
                    </div>
                {% endif %}
                <!-- End IF the viewer is the creator of the photo -->
            </h3>

        </div>
        <!--  -->
    </div>
    <!-- Post image -->
    <div class="imgBx" id="photo-{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>
    <!-- -->

    <div class="bottom">
        <!-- like and share buttons -->
        <div class="actionBtns">
            <div class="left">
								<span class="heart">
                                    <a href="{% url 'like_pet_photo' pk=photo.pk %}">
                                        <!-- if user has liked the photo -->
                                        {% if request.user.is_authenticated and photo|is_liked_by_user:request.user %}
                                            <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                            <!-- else -->
                                        {% else %}
                                            <i class="fa-regular fa-heart"></i>
                                        {% endif %}
                                    </a>
								</span>
                <a href="share">
                    <i class="fa-solid fa-share"></i>
                </a>
            </div>
        </div>
        <!-- -->

        <a href="#">
            <p class="likes">{{ photo.photolike_set.count }} likes</p>
        </a>

        <!-- tagged pets -->

        {% for pet in  photo.pets.all %}

            <a href="{% url 'details pet' username=pet.user.profile.get_profile_name|lower slug=pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}

        <!--  -->

        <a href="{% url 'details photo' pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">{{ photo.created_at|date:'d M yy' }}</h5>

        {% for comment in photo.photocomment_set.all %}
            <div class="comments">
                <div class="top">
                    <div class="userDetails">
                        <div class="comment-data">
                            <div class="profilepic">
                                <div class="profile_img">
                                    {% if comment.user.profile.profile_picture %}
                                        <div class="image">
                                            <!-- User Profile Image -->
                                            <img src="{{ comment.user.profile.profile_picture }}" alt="img8">
                                            
                                        </div>
                                    {% else %}
                                        <div class="image">
                                            <!-- Default User Profile Image -->
                                            <img src="{% static 'images/person.png' %}" alt="img8">
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <p>

                                <a href="{% url 'details_profile' pk=comment.user.pk %}">{{ comment.user.profile.get_short_name|default:"Anonymous" }}:</a>
                                <!-- User Comment -->
                                {{ comment.text }}

                            </p>
                        </div>
                        <span>{{ comment.created_at|date:'d M yy' }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- End Comments Section -->

        <!-- add comments section -->
        <div class="addComments">

            <form method="post" action="{% url 'add_comment' photo_id=photo.pk %}">
                <label for="id_body">Body:</label>
                {{ comment_form }}
                <button type="submit">Post</button>
                {% csrf_token %}
            </form>
        </div>
        <!--  -->
    </div>
</div>

petstagram/templates/partials/pet_photos_list.html
{% load static %}


{% for photo in photo_list %}
    <!-- IF Photos Start Pet Photos Post Section -->

    <!-- Start Pet Photo Post -->
    {% include 'partials/pet_photo_list_items.html' with photo=photo %}
    <!-- End  Pet Photo Post -->


    <!-- IF Photos End Pet Photos Post Section -->
{% empty %}
    <!-- IF NOT Photos Show No Post Image -->
    <img class="no-posts" src="{% static '/images/no_posts.png' %}" alt="no posts image">
{% endfor %}